// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.0.0
// source: app/model/service.proto

package model

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_app_model_service_proto protoreflect.FileDescriptor

var file_app_model_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x1a, 0x18, 0x61, 0x70, 0x70, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xc8, 0x04, 0x0a, 0x09, 0x49,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x27, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x1a, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x00, 0x12, 0x25, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0b, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x04, 0x53, 0x68, 0x6f, 0x77,
	0x12, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x0b, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x12, 0x29, 0x0a, 0x07,
	0x53, 0x68, 0x6f, 0x77, 0x41, 0x6c, 0x6c, 0x12, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x77, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x0d, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x2b,
	0x0a, 0x08, 0x53, 0x68, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0c, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x1a, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x00, 0x12, 0x25, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0b, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0b, 0x41, 0x64, 0x64,
	0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x1a, 0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0c, 0x45, 0x64,
	0x69, 0x74, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x12, 0x0f, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x1a, 0x0d, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x12, 0x0f,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x1a,
	0x0d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00,
	0x12, 0x33, 0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x77, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x12, 0x0c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4b, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_app_model_service_proto_goTypes = []interface{}{
	(*Item)(nil),         // 0: model.Item
	(*Empty)(nil),        // 1: model.Empty
	(*User)(nil),         // 2: model.User
	(*Kategori)(nil),     // 3: model.Kategori
	(*Status)(nil),       // 4: model.Status
	(*ItemList)(nil),     // 5: model.ItemList
	(*UserList)(nil),     // 6: model.UserList
	(*KategoriList)(nil), // 7: model.KategoriList
}
var file_app_model_service_proto_depIdxs = []int32{
	0,  // 0: model.Inventory.AddItem:input_type -> model.Item
	0,  // 1: model.Inventory.GetItem:input_type -> model.Item
	0,  // 2: model.Inventory.Show:input_type -> model.Item
	0,  // 3: model.Inventory.ShowAll:input_type -> model.Item
	1,  // 4: model.Inventory.ShowItem:input_type -> model.Empty
	2,  // 5: model.Inventory.Register:input_type -> model.User
	1,  // 6: model.Inventory.ShowUser:input_type -> model.Empty
	2,  // 7: model.Inventory.Login:input_type -> model.User
	2,  // 8: model.Inventory.GetUser:input_type -> model.User
	3,  // 9: model.Inventory.AddKategori:input_type -> model.Kategori
	3,  // 10: model.Inventory.EditKategori:input_type -> model.Kategori
	3,  // 11: model.Inventory.DeleteKategori:input_type -> model.Kategori
	1,  // 12: model.Inventory.ShowKategori:input_type -> model.Empty
	4,  // 13: model.Inventory.AddItem:output_type -> model.Status
	0,  // 14: model.Inventory.GetItem:output_type -> model.Item
	0,  // 15: model.Inventory.Show:output_type -> model.Item
	5,  // 16: model.Inventory.ShowAll:output_type -> model.ItemList
	5,  // 17: model.Inventory.ShowItem:output_type -> model.ItemList
	4,  // 18: model.Inventory.Register:output_type -> model.Status
	6,  // 19: model.Inventory.ShowUser:output_type -> model.UserList
	4,  // 20: model.Inventory.Login:output_type -> model.Status
	2,  // 21: model.Inventory.GetUser:output_type -> model.User
	4,  // 22: model.Inventory.AddKategori:output_type -> model.Status
	4,  // 23: model.Inventory.EditKategori:output_type -> model.Status
	4,  // 24: model.Inventory.DeleteKategori:output_type -> model.Status
	7,  // 25: model.Inventory.ShowKategori:output_type -> model.KategoriList
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_app_model_service_proto_init() }
func file_app_model_service_proto_init() {
	if File_app_model_service_proto != nil {
		return
	}
	file_app_model_database_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_model_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_model_service_proto_goTypes,
		DependencyIndexes: file_app_model_service_proto_depIdxs,
	}.Build()
	File_app_model_service_proto = out.File
	file_app_model_service_proto_rawDesc = nil
	file_app_model_service_proto_goTypes = nil
	file_app_model_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InventoryClient is the client API for Inventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InventoryClient interface {
	AddItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Status, error)
	GetItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error)
	Show(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error)
	ShowAll(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ItemList, error)
	ShowItem(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ItemList, error)
	Register(ctx context.Context, in *User, opts ...grpc.CallOption) (*Status, error)
	ShowUser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error)
	Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*Status, error)
	GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	AddKategori(ctx context.Context, in *Kategori, opts ...grpc.CallOption) (*Status, error)
	EditKategori(ctx context.Context, in *Kategori, opts ...grpc.CallOption) (*Status, error)
	DeleteKategori(ctx context.Context, in *Kategori, opts ...grpc.CallOption) (*Status, error)
	ShowKategori(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KategoriList, error)
}

type inventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryClient(cc grpc.ClientConnInterface) InventoryClient {
	return &inventoryClient{cc}
}

func (c *inventoryClient) AddItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/model.Inventory/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/model.Inventory/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) Show(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/model.Inventory/Show", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) ShowAll(ctx context.Context, in *Item, opts ...grpc.CallOption) (*ItemList, error) {
	out := new(ItemList)
	err := c.cc.Invoke(ctx, "/model.Inventory/ShowAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) ShowItem(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ItemList, error) {
	out := new(ItemList)
	err := c.cc.Invoke(ctx, "/model.Inventory/ShowItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) Register(ctx context.Context, in *User, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/model.Inventory/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) ShowUser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UserList, error) {
	out := new(UserList)
	err := c.cc.Invoke(ctx, "/model.Inventory/ShowUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/model.Inventory/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) GetUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/model.Inventory/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) AddKategori(ctx context.Context, in *Kategori, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/model.Inventory/AddKategori", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) EditKategori(ctx context.Context, in *Kategori, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/model.Inventory/EditKategori", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) DeleteKategori(ctx context.Context, in *Kategori, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/model.Inventory/DeleteKategori", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryClient) ShowKategori(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*KategoriList, error) {
	out := new(KategoriList)
	err := c.cc.Invoke(ctx, "/model.Inventory/ShowKategori", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServer is the server API for Inventory service.
type InventoryServer interface {
	AddItem(context.Context, *Item) (*Status, error)
	GetItem(context.Context, *Item) (*Item, error)
	Show(context.Context, *Item) (*Item, error)
	ShowAll(context.Context, *Item) (*ItemList, error)
	ShowItem(context.Context, *Empty) (*ItemList, error)
	Register(context.Context, *User) (*Status, error)
	ShowUser(context.Context, *Empty) (*UserList, error)
	Login(context.Context, *User) (*Status, error)
	GetUser(context.Context, *User) (*User, error)
	AddKategori(context.Context, *Kategori) (*Status, error)
	EditKategori(context.Context, *Kategori) (*Status, error)
	DeleteKategori(context.Context, *Kategori) (*Status, error)
	ShowKategori(context.Context, *Empty) (*KategoriList, error)
}

// UnimplementedInventoryServer can be embedded to have forward compatible implementations.
type UnimplementedInventoryServer struct {
}

func (*UnimplementedInventoryServer) AddItem(context.Context, *Item) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddItem not implemented")
}
func (*UnimplementedInventoryServer) GetItem(context.Context, *Item) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (*UnimplementedInventoryServer) Show(context.Context, *Item) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}
func (*UnimplementedInventoryServer) ShowAll(context.Context, *Item) (*ItemList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowAll not implemented")
}
func (*UnimplementedInventoryServer) ShowItem(context.Context, *Empty) (*ItemList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowItem not implemented")
}
func (*UnimplementedInventoryServer) Register(context.Context, *User) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedInventoryServer) ShowUser(context.Context, *Empty) (*UserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowUser not implemented")
}
func (*UnimplementedInventoryServer) Login(context.Context, *User) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedInventoryServer) GetUser(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedInventoryServer) AddKategori(context.Context, *Kategori) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKategori not implemented")
}
func (*UnimplementedInventoryServer) EditKategori(context.Context, *Kategori) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditKategori not implemented")
}
func (*UnimplementedInventoryServer) DeleteKategori(context.Context, *Kategori) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKategori not implemented")
}
func (*UnimplementedInventoryServer) ShowKategori(context.Context, *Empty) (*KategoriList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowKategori not implemented")
}

func RegisterInventoryServer(s *grpc.Server, srv InventoryServer) {
	s.RegisterService(&_Inventory_serviceDesc, srv)
}

func _Inventory_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).AddItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).Show(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_ShowAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).ShowAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/ShowAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).ShowAll(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_ShowItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).ShowItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/ShowItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).ShowItem(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).Register(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_ShowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).ShowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/ShowUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).ShowUser(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).Login(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).GetUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_AddKategori_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Kategori)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).AddKategori(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/AddKategori",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).AddKategori(ctx, req.(*Kategori))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_EditKategori_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Kategori)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).EditKategori(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/EditKategori",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).EditKategori(ctx, req.(*Kategori))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_DeleteKategori_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Kategori)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).DeleteKategori(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/DeleteKategori",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).DeleteKategori(ctx, req.(*Kategori))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inventory_ShowKategori_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServer).ShowKategori(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Inventory/ShowKategori",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServer).ShowKategori(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inventory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.Inventory",
	HandlerType: (*InventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItem",
			Handler:    _Inventory_AddItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _Inventory_GetItem_Handler,
		},
		{
			MethodName: "Show",
			Handler:    _Inventory_Show_Handler,
		},
		{
			MethodName: "ShowAll",
			Handler:    _Inventory_ShowAll_Handler,
		},
		{
			MethodName: "ShowItem",
			Handler:    _Inventory_ShowItem_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Inventory_Register_Handler,
		},
		{
			MethodName: "ShowUser",
			Handler:    _Inventory_ShowUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Inventory_Login_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Inventory_GetUser_Handler,
		},
		{
			MethodName: "AddKategori",
			Handler:    _Inventory_AddKategori_Handler,
		},
		{
			MethodName: "EditKategori",
			Handler:    _Inventory_EditKategori_Handler,
		},
		{
			MethodName: "DeleteKategori",
			Handler:    _Inventory_DeleteKategori_Handler,
		},
		{
			MethodName: "ShowKategori",
			Handler:    _Inventory_ShowKategori_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/model/service.proto",
}
